def label = "${env.JOB_NAME}-${env.BUILD_ID}"
def version = readMavenPom().getVersion().replaceAll("SNAPSHOT","").replaceAll("-","")
def artifact = readMavenPom().getArtifactId()
def museumaddress = "chartmeseum.juliusbaer.com"
 
podTemplate(label: label, containers: [
    containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'helm', image: 'vfarcic/helm:2.9.1', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]) {
    node(label) {
 
        stage('deploy') {
             try {
                    container("helm") {
                           k8sUpgrade(artifact, museumaddress)
                    }
                    container("kubectl") {
                           k8sRollout(artifact)
                    }
             } catch(e) {
                    container("helm") {
                           k8sRollback(artifact)
                    }
             }
       }
 
    }
}