def label = "${env.JOB_NAME}-${env.BUILD_ID}"
def version = readMavenPom().getVersion().replaceAll("SNAPSHOT","").replaceAll("-","")
def artifact = readMavenPom().getArtifactId()
def museumaddress = "chartmeseum.juliusbaer.com"
 
podTemplate(label: label, containers: [
    containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
    containerTemplate(name: 'maven', image: 'maven:3.6.0-jdk-8-alpine', ttyEnabled: true, command: 'cat')
    containerTemplate(name: 'helm', image: 'vfarcic/helm:2.9.1', command: 'cat', ttyEnabled: true)
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
    persistentVolumeClaim(mountPath: '/root/.m2/repository', claimName: 'maven-repo', readOnly: false)
  ]) {
    node(label) {
 
        stage('mavenbuild') {
            container('maven') {
                           sh 'mvn -B clean package'
            }
        }
        stage('dockerbuild') {
            container('docker') {
                           k8sBuildImage(artifact:version)
                    k8sPushImage(artifact:version)
            }
        }
        stage('do some helm work') {
            container('helm') {
                    k8sPushHelm(artifact, version, museumaddress)
            }
        }
    }
}